SET REFERENTIAL_INTEGRITY FALSE;
DELETE FROM app_user_roles;
DELETE FROM app_user_profile_image;
DELETE FROM event_event_image;
DELETE FROM events_app_users;
TRUNCATE TABLE event RESTART IDENTITY;
TRUNCATE TABLE app_user RESTART IDENTITY;
TRUNCATE TABLE image RESTART IDENTITY;