spring:
  liquibase:
    change-log: classpath:db/master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true

application:
  security:
    jwt:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
