--liquibase formatted sql
--changeset Patryk Depka:0013-1
INSERT INTO `event` (`uuid`, `name`, `event_type`, `date_time`, `language`, `admission`, `city`, `location`, `address`, `organizer_id`, `description`)
VALUES
    (UUID(), 'Java Dev Talks #1', 'MEETING', CONCAT(YEAR(CURDATE()), '-01-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #2', 'MEETING', CONCAT(YEAR(CURDATE()), '-02-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #3', 'MEETING', CONCAT(YEAR(CURDATE()), '-03-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #4', 'MEETING', CONCAT(YEAR(CURDATE()), '-04-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #5', 'MEETING', CONCAT(YEAR(CURDATE()), '-05-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #6', 'MEETING', CONCAT(YEAR(CURDATE()), '-06-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #7', 'MEETING', CONCAT(YEAR(CURDATE()), '-07-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #8', 'MEETING', CONCAT(YEAR(CURDATE()), '-08-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #9', 'MEETING', CONCAT(YEAR(CURDATE()), '-09-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #10', 'MEETING', CONCAT(YEAR(CURDATE()), '-10-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #11', 'MEETING', CONCAT(YEAR(CURDATE()), '-11-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #12', 'MEETING', CONCAT(YEAR(CURDATE()), '-12-15T18:00'), 'polski', 'FREE', 'Rzeszów', 'WSIiZ', 'Sucharskiego 2, 35-225 Rzeszów', 2, 'Spotkanie rzeszowskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #1', 'MEETING', CONCAT(YEAR(CURDATE()), '-01-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #2', 'MEETING', CONCAT(YEAR(CURDATE()), '-02-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #3', 'MEETING', CONCAT(YEAR(CURDATE()), '-03-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #4', 'MEETING', CONCAT(YEAR(CURDATE()), '-04-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #5', 'MEETING', CONCAT(YEAR(CURDATE()), '-05-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #6', 'MEETING', CONCAT(YEAR(CURDATE()), '-06-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #7', 'MEETING', CONCAT(YEAR(CURDATE()), '-07-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #8', 'MEETING', CONCAT(YEAR(CURDATE()), '-08-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #9', 'MEETING', CONCAT(YEAR(CURDATE()), '-09-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #10', 'MEETING', CONCAT(YEAR(CURDATE()), '-10-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #11', 'MEETING', CONCAT(YEAR(CURDATE()), '-11-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.'),
    (UUID(), 'Java Dev Talks #12', 'MEETING', CONCAT(YEAR(CURDATE()), '-12-15T18:00'), 'polski', 'FREE', 'Warszawa', 'Politechnika Warszawska', 'Pl. Politechniki 1, 00-661 Warszawa', 2, 'Spotkanie warszawskiej grupy pasjonatów języka Java.');